#!/usr/bin/env bash
# Emit test-summary.json — the authoritative per-suite pass/fail/ignore
# counts, generated by CI so the documentation never has to hard-code them.
#
# Run from the repository root: bash scripts/emit-test-summary.sh
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/test-summary.json"
COMMIT="$(git -C "$ROOT" rev-parse --short=7 HEAD 2>/dev/null || echo "unknown")"

# Count one crate's `cargo test` output. Prints "<passed> <failed> <ignored>".
count_one() {
  local dir="$1"; shift
  ( cd "$ROOT/$dir" && rm -f Cargo.lock && cargo test "$@" 2>&1 ) \
  | awk '
    /test result:/ {
      for (i = 1; i <= NF; i++) {
        if ($i == "passed;")      { p += $(i-1) }
        else if ($i == "failed;") { f += $(i-1) }
        else if ($i == "ignored") { ig += $(i-1) }
      }
    }
    END { printf "%d %d %d", p + 0, f + 0, ig + 0 }
  '
}

read -r K_P K_F K_I < <(count_one aegis-kernel)
read -r M_P M_F M_I < <(count_one aegis)
read -r U_P U_F U_I < <(count_one uefi-boot)

TP=$((K_P + M_P + U_P))
TF=$((K_F + M_F + U_F))

cat > "$OUT" <<JSON
{
  "commit": "$COMMIT",
  "kernel": { "passed": $K_P, "failed": $K_F, "ignored": $K_I },
  "model":  { "passed": $M_P, "failed": $M_F, "ignored": $M_I },
  "uefi":   { "passed": $U_P, "failed": $U_F, "ignored": $U_I },
  "total_passed": $TP,
  "total_failed": $TF
}
JSON
cat "$OUT"
